# When anyone pushes to npm branch in this repo, the package will be published to npm.
# https://docs.npmjs.com/trusted-publishers is active in this repo
name: Publish package to npm

on:
  push:
    branches: [ npm ]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Npm Install
        run: |
          npm install
      - name: building package
        run: |
          npm run build
      - name: Tests with coverage
        run: |
          npm run cover
      - name: Publishing package to npm repository
        run: |
          node .github/workflows/js/validatePackage.cjs
          npm publish --access public
